import React from 'react'
import Script from 'next/script'

const Contact = () => {
  return (
    <div>
        <script>
            {`alert("wlcome to contectv page ")`}
        </script>
      I am contact
    </div>
  )
}

export default Contact

export const metadata = {
    title: "contect",
    description: "Generated by create next app",
  };